/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/ui/AppButton.vue')['default']
    AppCard: typeof import('./components/ui/AppCard.vue')['default']
    AppFooter: typeof import('./components/layouts/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/layouts/AppNavbar.vue')['default']
    AppPagination: typeof import('./components/ui/AppPagination.vue')['default']
    AppSkeleton: typeof import('./components/ui/AppSkeleton.vue')['default']
    AppTextField: typeof import('./components/ui/AppTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
